name: Build, Test, Auto-Merge to Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - test

jobs:
  build_and_test:
    name: Quality Gate Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' 

      - name: Restore and Build Project
        run: dotnet build --configuration Release


  auto_merge:
    name: ðŸ¤– Automatic Merge
    
    needs: build_and_test 
    runs-on: ubuntu-latest
    if: success() && github.event_name == 'pull_request' && github.base_ref == 'test'
  
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Merge PR to Test Branch
        uses: pascalgn/automerge-action@v0.17.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          PULL_REQUEST: ${{ github.event.pull_request.number }}